const floorGraphicsCategories= [
    "Way Finding",
    "Directional Signs",
    "Symbols",
    "Fire Safety",
    "Chemical Safety",
    "Environment",
    "Health & Yoga",
    "House Keeping",
    "Material Handling",
    "Electrical Safety",
    "PPE",
    "COVID",
    "Foot Marks",
    "Beauty & Fashion",
    "Kids",
    "Emotion",
    "Food",
    "Tools",
    "Music",
    "Direction",
    "Education",
    "Gestures",
    "Science",
    "Avatars",
  ];
  export default floorGraphicsCategories;