const posterCategories = [
    "Fire Safety",
    "Environment",
    "House Keeping",
    "Material Handling",
    "Quality",
    "Electrical Safety",
    "Health & Yoga",
    "PPE",
    "Accident",
    "Motivational",
    "Gender Equality",
    "Women Empowerment",
    "Chemical Safety",
    "General Safety",
    "Inclusive Workplace",
    "Team Work",
    "COVID",
    "Traffic Safety",
    "General Information",
    "Goals",
  ];
  export default posterCategories;